import Coffee from "../models/coffee.js";

const db = require("./db");

export default function coffeeSeeder() {
  db.then(async ({ disconnect }) => {
    await Coffee.insertMany([
      {
        title: "Ява Золотая",
        description: "tut descr",
        tags: "tut tag",
        region: "Сунда",
        type: "Фильтр",
        acidity: "tut kislota",
      },
      {
        title: "Уганда Бузи Черри",
        description: "tut descr",
        tags: "tut tag",
        region: "Западная Уганда",
        type: "Фильтр",
        acidity: "tut kislota",
      },
      {
        title: "Колумбия Габриэль Кастаньо Анаэробная обработка",
        description: "tut descr",
        tags: "tut tag",
        region: "Уила, Сан-Адольфо",
        type: "Фильтр",
        acidity: "tut kislota",
      },
      {
        title: "Эфиопии под молочко",
        description: "tut descr",
        tags: "tut tag",
        region: "Иргачиф",
        type: "Эспрессо",
        acidity: "tut kislota",
      },
      {
        title: "Колумбии под молочко",
        description: "tut descr",
        tags: "tut tag",
        region: "Нариньо",
        type: "Эспрессо",
        acidity: "tut kislota",
      },
      {
        title: "Бурунди Бузирагухиндва",
        description: "tut descr",
        tags: "tut tag",
        region: "Каянза",
        type: "Фильтр",
        acidity: "tut kislota",
      },
      {
        title: "Колумбия Асиведо-Питалито",
        description: "tut descr",
        tags: "tut tag",
        region: "Уила, Асиведо, Питалито",
        type: "Эспрессо",
        acidity: "tut kislota",
      },
      {
        title: "Кения Гатаити АА из бочки",
        description: "tut descr",
        tags: "tut tag",
        region: "Округ Ньери, Тету",
        type: "Фильтр",
        acidity: "tut kislota",
      },
      {
        title: "Колумбия Пасто Седе из бочки",
        description: "tut descr",
        tags: "tut tag",
        region: "Нариньо",
        type: "Фильтр",
        acidity: "tut kislota",
      },
      {
        title: "Эфиопия Лалиса",
        description: "tut descr",
        tags: "tut tag",
        region: "Иргачиф",
        type: "Эспрессо",
        acidity: "tut kislota",
      },
      {
        title: "Бразилия Наталья Гарсия",
        description: "tut descr",
        tags: "tut tag",
        region: "Минас Жерайс, Кампо дас Вертентес",
        type: "Фильтр",
        acidity: "tut kislota",
      },
      {
        title: "Бразилия Ягуара",
        description: "tut descr",
        tags: "tut tag",
        region: "Минас Жерайс, Кампо дас Вертентес",
        type: "Фильтр",
        acidity: "tut kislota",
      },
      {
        title: "Бурунди Мбиризи",
        description: "tut descr",
        tags: "tut tag",
        region: "Каянза",
        type: "Фильтр",
        acidity: "tut kislota",
      },
      {
        title: "Индонезия Фринса Лактик",
        description: "tut descr",
        tags: "tut tag",
        region: "Сунда",
        type: "Фильтр",
        acidity: "tut kislota",
      },
      {
        title: "Кения Кангочо",
        description: "tut descr",
        tags: "tut tag",
        region: "Ньери",
        type: "Фильтр",
        acidity: "tut kislota",
      },
      {
        title: "Кения Каримикуй",
        description: "tut descr",
        tags: "tut tag",
        region: "Кириньяга",
        type: "Фильтр",
        acidity: "tut kislota",
      },
      {
        title: "Колумбия Ла Виргиния",
        description: "tut descr",
        tags: "tut tag",
        region: "Уила",
        type: "Фильтр",
        acidity: "tut kislota",
      },
      {
        title: "Колумбия Рафаэль Айа",
        description: "tut descr",
        tags: "tut tag",
        region: "Уила",
        type: "Фильтр",
        acidity: "tut kislota",
      },
      {
        title: "Колумбия Рафаэль Айа Катурра 90",
        description: "tut descr",
        tags: "tut tag",
        region: "Уила",
        type: "Фильтр",
        acidity: "tut kislota",
      },
      {
        title: "Коста-Рика Монтерога",
        description: "tut descr",
        tags: "tut tag",
        region: "Тараззу, Сан Исидро",
        type: "Фильтр",
        acidity: "tut kislota",
      },
      {
        title: "Суматра Гайо Маунтайн",
        description: "tut descr",
        tags: "tut tag",
        region: "Ачех",
        type: "Фильтр",
        acidity: "цитрусово-винная, выраженная",
      },
      {
        title: "Сладкая Бразилия Кармо Де Минас",
        description: "tut descr",
        tags: "tut tag",
        region: "Кармо Де Минас",
        type: "Эспрессо",
        acidity: "ниже среднего",
      },
      {
        title: "Эфиопия Анасора",
        description: "tut descr",
        tags: "tut tag",
        region: "Оромия",
        type: "Эспрессо",
        acidity: "tut kislota",
      },
      {
        title: "Колумбия Сол Насиенте",
        description: "tut descr",
        tags: "tut tag",
        region: "Колумбия",
        type: "Фильтр",
        acidity: "умеренная, преимущественно яблочная",
      },
      {
        title: "Колумбия Буена Виста",
        description: "tut descr",
        tags: "tut tag",
        region: "Колумбия",
        type: "Фильтр",
        acidity: "яркая яблочная, лимонная",
      },
      {
        title: "Яркая Танзания Умоджа Улулу",
        description: "tut descr",
        tags: "tut tag",
        region: "Мбея",
        type: "Фильтр",
        acidity: "ниже среднего",
      },
      {
        title: "Сбалансированный бленд Бразилии",
        description: "tut descr",
        tags: "tut tag",
        region: "Бразилия",
        type: "Эспрессо",
        acidity: "ниже среднего",
      },
      {
        title: "Сбалансированный бленд двойной Эфиопии",
        description: "tut descr",
        tags: "tut tag",
        region: "Эфиопия",
        type: "Эспрессо",
        acidity: "средняя",
      },
      {
        title: "Сбалансированный бленд Бразилии и Эфиопии",
        description: "tut descr",
        tags: "tut tag",
        region: "Бразилия и Эфиопия",
        type: "Эспрессо",
        acidity: "средняя",
      },
      {
        title: "Сбалансированный бленд Колумбии",
        description: "tut descr",
        tags: "tut tag",
        region: "Колумбия",
        type: "Эспрессо",
        acidity: "средняя",
      },
      {
        title: "Сбалансированный бленд Арабики и Робусты",
        description: "tut descr",
        tags: "tut tag",
        region: "Бразилия и Индия",
        type: "Эспрессо",
        acidity: "низкая",
      },
      {
        title: "Сбалансированный бленд Суматры и Бразилии",
        description: "tut descr",
        tags: "tut tag",
        region: "Суматра и Бразилия",
        type: "Эспрессо",
        acidity: "средняя",
      },
      {
        title: "Эфиопия Керреча",
        description: "tut descr",
        tags: "tut tag",
        region: "Керреча",
        type: "Эспрессо",
        acidity: "средняя, винная и цитрусовая",
      },
      {
        title: "Яркая Танзания Умоджа Улулу",
        description: "tut descr",
        tags: "tut tag",
        region: "Мбея",
        type: "Фильтр",
        acidity: "tut kislota",
      },
      {
        title: "Колумбия Таби Лэнд",
        description: "tut descr",
        tags: "tut tag",
        region: "Колумбия",
        type: "Фильтр",
        acidity: "тёмных ягод и красного вина",
      },
      {
        title: "Сочная Танзания Умоджа Улулу",
        description: "tut descr",
        tags: "tut tag",
        region: "Мбея",
        type: "Фильтр",
        acidity: "tut kislota",
      },
      {
        title: "Сочная Эфиопия Банко Готете ПБ",
        description: "tut descr",
        tags: "tut tag",
        region: "asdasda",
        type: "Фильтр",
        acidity: "яблочная и цитрусовая",
      },
      {
        title: "Сочная Колумбия Апонте",
        description: "tut descr",
        tags: "tut tag",
        region: "Нариньо",
        type: "Фильтр",
        acidity: "tut kislota",
      },
      {
        title: "Сочная Кения Мугага Гатина",
        description: "tut descr",
        tags: "tut tag",
        region: "Мугага",
        type: "Фильтр",
        acidity: "tut kislota",
      },
      {
        title: "Сочная Бразилия Альта Виста",
        description: "tut descr",
        tags: "tut tag",
        region: "Бразилия",
        type: "Фильтр",
        acidity: "tut kislota",
      },
      {
        title: "Сладкая Колумбия Декаф эль Карамель (эспрессо)",
        description: "tut descr",
        tags: "tut tag",
        region: "Колумбия",
        type: "Эспрессо",
        acidity: "tut kislota",
      },
      {
        title: "Эфиопия Керреча",
        description: "tut descr",
        tags: "tut tag",
        region: "Керреча",
        type: "Фильтр",
        acidity: "средняя, винная и цитрусовая",
      },
      {
        title: "Сладкая Бразилия Кармо Де Минас (фильтр)",
        description: "tut descr",
        tags: "tut tag",
        region: "Кармо Де Минас",
        type: "Фильтр",
        acidity: "tut kislota",
      },
      {
        title: "Яркая Бразилия Фазенда Чапада",
        description: "tut descr",
        tags: "tut tag",
        region: "Кармо Де Минас",
        type: "Фильтр",
        acidity: "tut kislota",
      },
    ]);
    disconnect();
  }).catch((err) => {
    console.error(err);
  });
}
